Fix spi loading (#480)
We should ignore NoClassDefFoundError, this improves the experience when using incremental compilation in intellij because some compiled classes might still be lingering around for removed services.